### PR TITLE
added search functionality

### LINKED ISSUE #4: Apply the search Functionality with proper search suggestions

### PR DESCRIPTION
**Pull request by designdotdevanshu**
fixes #4 
Added the Search Functionality.

### CODE REVIEW

**Comment by Vaani-pathariya** [comment]
Though I think the codes are fine , changes were not reflected on the screen after entering the dates . Can you provide any input on that ?

**Comment by designdotdevanshu** [comment]
> Though I think the codes are fine , changes were not reflected on the screen after entering the dates . Can you provide any input on that ? @designdotdevanshu

Hey thanks for responding. I have fixed the issue with dates. Now check and let me know if it's working or not.

**Comment by Vaani-pathariya** [comment]
The earlier issue works fine now , but change the ranges bit more to display the right events such as the following one :
image<br>
however
image

**Comment by designdotdevanshu** [comment]
Try 10/18/2023 - 10/20/2023 as a range
The date is in "mm/dd/yyyy" format. Should I fix that also?

**Comment by Vaani-pathariya** [comment]
Yes , change the date to dd/mm/yyyy and make the range such that the event is visible at 19/10/2023-20/10/2023

**Comment by designdotdevanshu** [comment]
Hey, I have fixed the date range part but the mm/dd/yyyy format is default and we can't change that. Either we can change the format on the events to mm/dd/yyyy from dd/mm/yyyy.

Like this 
image

**Comment by Vaani-pathariya** [comment]
Just do the range part , leave the date as it is then

**Comment by designdotdevanshu** [comment]
I have pushed the code. Please check.

**Comment by Vaani-pathariya** [comment]
Good work !!

**Pull request merged**
