### PR TITLE
[Enhancement]: adding an api for contact us form

### LINKED ISSUE #6: Create an API for contact Us page

### PR DESCRIPTION
**Pull request by Rohit-Sharmaa**
Description
I have added  a post request api in the backend/contactRoute.js file which will parse the data from the contact-us form.
Right know we don't have any database or something like that so i have not able to link the api with the db and also not able to  put any type of data in the database but in future when we have database we can put data in database  by using this api . 

Fixes #6

### CODE REVIEW

**Comment by Rohit-Sharmaa** [comment]
@Vaani-pathariya  i have added an api for this I hope you review my code and give me feedback ??

**Comment by Vaani-pathariya** [comment]
@Rohit-Sharmaa  please check backend branch , and move the submit-form end point there. Don't create a separate Backend folder in master branch

**Comment by Rohit-Sharmaa** [comment]
@Vaani-pathariya  yah sure i will do that

**Comment by Rohit-Sharmaa** [comment]
@Vaani-pathariya  is this okay ??

**Pull request closed without merging**
