### PR TITLE
Update Fetch All Events API to fetch events of specific user

### LINKED ISSUE #45: [Bug]: Fetch All Events API is fetching events of other users
####Description
Fetch All Events API is fetching events of other users.

####What should happen:
Events of user should be fetched.

####What should happen instead:
Events of all users are fetched.

**To Reproduce**
1. Sign up using name, email, password and confirm-password for two users.
2. Login using email and password and user receives token on successful login .
3. Add Events from both users.
4. Test Fetch All Events API by giving token in authorization request header.

### PR DESCRIPTION
**Pull request by Hawkeye2108**
Fix #45 
Updated Fetch All Events API to fetch events of specific user.

### CODE REVIEW

**Comment by Vaani-pathariya** [comment]
This pull request has a conflict , resolve it on your end and then create a pull request

**Comment by Hawkeye2108** [comment]
@Vaani-pathariya I have resolved the conflict, please check it.

**Comment by Vaani-pathariya** [comment]
Great work @Hawkeye2108

**Comment by Hawkeye2108** [comment]
Thank You @Vaani-pathariya

**Pull request merged**
