### PR TITLE
fix: yt logo not visible for smaller screens

### LINKED ISSUE #28: Youtube logo is not visible for smaller screens
image<br>
image

### PR DESCRIPTION
**Pull request by designdotdevanshu**
fixes #28 
Youtube logo is not visible for smaller screens

Screen Shot 2023-10-14 at 23 11 27

### CODE REVIEW

**Comment by gandholi-kumar** [comment]
Hi @designdotdevanshu 
Have you tested in landscape mode? From my analysis we still truncate the last icons

**Comment by designdotdevanshu** [comment]
> Hi @designdotdevanshu Have you tested in landscape mode? From my analysis last icons will still be truncated. (window height <600px)

We have to find another way to show them. We can't show them in one row.

**Comment by gandholi-kumar** [comment]
> > Hi @designdotdevanshu Have you tested in landscape mode? From my analysis last icons will still be truncated. (window height <600px)
> 
> We have to find another way to show them. We can't show them in one row.

Kindly get the confirmation from @Vaani-pathariya.

**Comment by designdotdevanshu** [comment]
Hey @gandholi-kumar We can do align that to bottom.
See this

[Screencast from 2023-10-16 17-40-47.webm](https://github.com/DSC-JSS-NOIDA/Foss-events2.0/assets/127396627/b85228e8-102a-43c6-a91f-45dd03090999)

**Comment by gandholi-kumar** [comment]
> Hey @gandholi-kumar @Vaani-pathariya We can do align that to bottom. See this
> 
>  Screencast.from.2023-10-16.17-40-47.webm

This could be one of the solution but in my opinion it would be great for mobile devices, if we could move the social icons as part of footer. Since the user will be more interested into the content than the social icons. 

@Vaani-pathariya  kindly provide your inputs.

**Note**: There is a CSS function `clamp()` which can be used for setting up the min, default and max size of content (font-size, etc).

**Comment by Vaani-pathariya** [comment]
> Hey @gandholi-kumar @Vaani-pathariya We can do align that to bottom. See this
> 
>  Screencast.from.2023-10-16.17-40-47.webm

I don't think this will be a good method to solve the issue. I want to make the side options scrollable for smaller screens , so that on scrolling , the further icons will be visible .
@designdotdevanshu  @gandholi-kumar  provide your inputs for the same.

**Pull request merged**
