### PR TITLE
Updated the font and other text attributes for the homepage

### LINKED ISSUE #27: Apply Queensides font to the website
Design link : https://www.figma.com/file/1JSMaoKNjNXYHn2ABc2ra3/Foss-events2.0?type=design&node-id=4717%3A1283&mode=design&t=NYnbA7Q4UQvLjTcU-1
image

### PR DESCRIPTION
**Pull request by IrfanSalim**
closes #27 

image

### CODE REVIEW

**Comment by Vaani-pathariya** [comment]
Great work ! 
Can you do the same for Events page as well ?

**Comment by IrfanSalim** [comment]
@Vaani-pathariya 
You want all the fonts on event page to be same?

**Comment by Vaani-pathariya** [comment]
> @Vaani-pathariya You want all the fonts on event page to be same?

No, just change the font of event cards

**Comment by IrfanSalim** [comment]
image

So for all the text inside the card right?

**Comment by Vaani-pathariya** [comment]
image
This way

**Comment by IrfanSalim** [comment]
image

or 

image

**Comment by Vaani-pathariya** [comment]
Below one is perfect !

**Comment by Vaani-pathariya** [comment]
Great work ! Thanks for your contribution !!

**Pull request merged**
